from pathlib import Path
from typing import Protocol
from uuid import UUID


class StorageAdapter(Protocol):
    def session_dir(self, session_id: UUID) -> Path: ...

    def audio_path(self, session_id: UUID) -> Path: ...

    def transcript_path(self, session_id: UUID) -> Path: ...

    async def delete_audio(self, session_id: UUID) -> None: ...

    async def delete_session_dir(self, session_id: UUID) -> None: ...
